// This file is generated by the build script, please do not edit.

pub const all = [_]@import("const.zig").Command {
    @import("commands/clone.zig").command,
    @import("commands/help.zig").command,
    @import("commands/uninstall.zig").command,
    @import("commands/update.zig").command,
    @import("commands/version.zig").command,
    @import("commands/ziglove.zig").command,
};
