// This file is generated by the build script, please do not edit.

pub const all = [_]@import("const.zig").Command {    @import("commands/clone.zig"),
    @import("commands/help.zig"),
    @import("commands/start.zig"),
    @import("commands/uninstall.zig"),
    @import("commands/update.zig"),
    @import("commands/version.zig"),
    @import("commands/ziglove.zig"),
};
