// This file is generated by the build script, please do not edit.

pub const all = [_]@import("const.zig").Definition {
    @import("commands/clone.zig").definition,
    @import("commands/help.zig").definition,
    @import("commands/uninstall.zig").definition,
    @import("commands/update.zig").definition,
    @import("commands/version.zig").definition,
    @import("commands/ziglove.zig").definition,
};
