//! Workspace - A CLI tool for managing GitHub repositories.
//! Provides functionalities for cloning repositories and generating VSCode workspace files.

const std = @import("std");
const constants = @import("const.zig");

/// A custom command list generated by build.zig
const commands = @import("commands.zig").all;

/// Specific imports
const parseArgs = @import("helpers/args.zig").parseArgs;
const ProcessPool = @import("helpers/pool.zig").ProcessPool;
const prune = @import("helpers/prune.zig").prune;

/// Entry point of the application.
/// Handles command-line arguments and dispatches to appropriate handlers.
pub fn main() !void {
    // Use GPA for long-lived allocations
    var GPA = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = GPA.deinit();
    const allocator = GPA.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);
}
