name: GitHub Actions Version Updater

on:
  schedule:
    - cron:  '30 06 * * *'

  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          pull_request_labels: "automerge"
      
      - name: Setup GitHub CLI and update version
        run: |
          # Get latest version and update INSTALL file
          VERSION=$(gh release list -L 1 --repo gaskam/workspace --exclude-drafts --exclude-pre-releases --json tagName,isDraft,isPrerelease -q ".[] | select(.isDraft==false and .isPrerelease==false) | .tagName")
          if [ -z "$VERSION" ]; then
            echo "Error: Could not retrieve version"
            exit 1
          fi
          
          echo "$VERSION" > INSTALL || { echo "Error writing to INSTALL file"; exit 1; }
          
          # Configure git and push changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add INSTALL
          git diff --staged --quiet || {
            git commit -m "Update version in INSTALL"
            git push origin HEAD:main || { echo "Error pushing changes"; exit 1; }
          }
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
